### ISSUE TITLE
Generator broken cause of classes

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trailpack-waterline#15]
Core using classes is under npm so now all other trailpack have to implement classes as well

```
Trace: [Error: FootprintService should be a class. It is a regular object]
    at TrailsApp.stop (/Users/jaumard/Downloads/testTrails/node_modules/trails/index.js:70:15)
    at /Users/jaumard/Downloads/testTrails/node_modules/trails/lib/trailpack.js:45:27
    at process._tickDomainCallback (node.js:400:9)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:118:18)
    at node.js:952:3
```

**Comment by jaumard** [comment]
Done

**Comment by jdell64** [comment]
Hey, does this mean that `trailpack-waterline` needs to be updated?

```
debug: trails event: trailpack:waterline:configured
error:
 Error: FootprintService should be a class. It is a regular object
    at C:\dev\happy_trails\grade_me\node_modules\trailpack-core\lib\context.js:47:15
    at C:\dev\happy_trails\grade_me\node_modules\lodash\lodash.js:12449:23
    at C:\dev\happy_trails\grade_me\node_modules\lodash\lodash.js:4332:15
    at baseForOwn (C:\dev\happy_trails\grade_me\node_modules\lodash\lodash.js:2731:24)
    at Function.mapValues (C:\dev\happy_trails\grade_me\node_modules\lodash\lodash.js:12448:7)
    at Object.bindMethods (C:\dev\happy_trails\grade_me\node_modules\trailpack-core\lib\context.js:45:14)
    at Core.configure (C:\dev\happy_trails\grade_me\node_modules\trailpack-core\index.js:31:37)
    at C:\dev\happy_trails\grade_me\node_modules\trails\lib\trailpack.js:56:26
    at process._tickDomainCallback (node.js:411:9)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by jaumard** [comment]
yes sometime npm doesn't install the latest version because of the `beta` number version and you need to install the last version manually to make it work.

**Comment by jdell64** [comment]
Sure enough... `trailpack-waterline@0.0.11`
Thanks for your help.
