### ISSUE TITLE
Cannot connect with waterline-mysql

### ISSUE THREAD

**Issue by simontong** [trailsjs/trailpack-waterline#51]
When I set up the following store in `config/database.js`:

```
stores : {
  mysql : {
    adapter: require(‘waterline-mysql'), 
    host: 'localhost',
    database: 'development',
    user: 'developer',
    password: 'somethingsupersecret'
  }
}
```

I get the following:

```
TypeError: Cannot read property 'host' of undefined
    at marshalConfig (/path/to/file/trails/node_modules/waterline-mysql/MySQLAdapter.js:530:17)
    at spawnConnection (/path/to/file/trails/node_modules/waterline-mysql/MySQLAdapter.js:502:44)
```

**Comment by tjwebb** [comment]
I don't think waterline-mysql is an active adapter. Try https://github.com/balderdashy/sails-mysql and let us know if you still have issues.
